### ISSUE TITLE
Does OFBiz have REST API and how to expose that?

### ISSUE THREAD

**Issue by kevintanhongann** [danwatford/docker-postgres-ofbiz#1]
I'm aware there is a https://github.com/girishvasmatkar/ofbiz-rest-impl for exposing some REST API.

Does this repo have this?

**Comment by danwatford** [comment]
Hi @kevintanhongann ,

No, this repository does not include the plugin.

OFBiz now has direct support for Docker. Please see https://github.com/apache/ofbiz-framework/blob/trunk/DOCKER.adoc  for instructions on building and running the official OFBiz repo with Docker.

You can add Girish's plugin to the build. Also, the OFBiz project is working on a new REST API. It's worth joining the USER mailing list and asking for an update there - https://ofbiz.apache.org/mailing-lists.html
